Update nani-cli

diff --git a/nani-cli b/nani-cli
--- a/nani-cli
+++ b/nani-cli
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-version_number="1.1"
+version_number="1.2"
 
 # UI
 
@@ -36,6 +36,27 @@ nth() {
 die() {
     printf "\33[2K\r\033[1;31m%s\033[0m\n" "$*" >&2
     exit 1
+
+
+rand_line() {
+    # Reads lines from stdin and prints one random line (portable; no shuf required)
+    awk 'BEGIN{srand()} {a[NR]=$0} END{if(NR>0) print a[int(rand()*NR)+1] }'
+}
+
+show_stats() {
+    # History format: ep_no<TAB>id<TAB>title
+    [ ! -f "$histfile" ] && die "History file not found"
+    total_entries="$(wc -l < "$histfile" | tr -d "[:space:]")"
+    unique_series="$(cut -f2 "$histfile" 2>/dev/null | sort -u | wc -l | tr -d "[:space:]")"
+    last_line="$(tail -n 1 "$histfile" 2>/dev/null)"
+    last_title="$(printf "%s" "$last_line" | cut -f3- )"
+    last_ep="$(printf "%s" "$last_line" | cut -f1 )"
+    printf "nani-cli stats\n"
+    printf "Entries: %s\n" "${total_entries:-0}"
+    printf "Unique series: %s\n" "${unique_series:-0}"
+    [ -n "$last_title" ] && printf "Last: %s (episode %s)\n" "$last_title" "$last_ep"
+    exit 0
+}
 }
 
 help_info() {
@@ -50,6 +71,10 @@ help_info() {
         Continue watching from history
       -d, --download
         Download the video instead of playing it
+      --random
+        Pick a random anime from search results
+      --stats
+        Show simple watch history stats
       -D, --delete
         Delete history
       -l, --logview
@@ -101,7 +126,7 @@ version_info() {
 }
 
 update_script() {
-    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/pystardust/nani-cli/master/nani-cli")" || die "Connection error"
+    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/NavineDevs/nani-cli/master/nani-cli")" || die "Connection error"
     update="$(printf '%s\n' "$update" | diff -u "$0" -)"
     if [ -z "$update" ]; then
         printf "Script is up to date :)\n"
@@ -382,10 +407,10 @@ agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefo
 allanime_refr="https://allmanga.to"
 allanime_base="allanime.day"
 allanime_api="https://api.${allanime_base}"
-mode="${ANI_CLI_MODE:-sub}"
-download_dir="${ANI_CLI_DOWNLOAD_DIR:-.}"
-log_episode="${ANI_CLI_LOG:-1}"
-quality="${ANI_CLI_QUALITY:-best}"
+mode="${NANI_CLI_MODE:-${ANI_CLI_MODE:-sub}}"
+download_dir="${NANI_CLI_DOWNLOAD_DIR:-${ANI_CLI_DOWNLOAD_DIR:-.}}"
+log_episode="${NANI_CLI_LOG:-${ANI_CLI_LOG:-1}}"
+quality="${NANI_CLI_QUALITY:-${ANI_CLI_QUALITY:-best}}"
 case "$(uname -a | cut -d " " -f 1,3-)" in
     *Darwin*) player_function="${ANI_CLI_PLAYER:-$(where_iina)}" ;;   # mac OS
     *ndroid*) player_function="${ANI_CLI_PLAYER:-android_mpv}" ;;     # Android OS (termux)
@@ -394,17 +419,17 @@ case "$(uname -a | cut -d " " -f 1,3-)" in
     *) player_function="${ANI_CLI_PLAYER:-$(where_mpv)}" ;;           # Linux OS
 esac
 
-no_detach="${ANI_CLI_NO_DETACH:-0}"
-exit_after_play="${ANI_CLI_EXIT_AFTER_PLAY:-0}"
-use_external_menu="${ANI_CLI_EXTERNAL_MENU:-0}"
-external_menu_normal_window="${ANI_CLI_EXTERNAL_MENU_NORMAL_WINDOW:-0}"
-skip_intro="${ANI_CLI_SKIP_INTRO:-0}"
+no_detach="${NANI_CLI_NO_DETACH:-${ANI_CLI_NO_DETACH:-0}}"
+exit_after_play="${NANI_CLI_EXIT_AFTER_PLAY:-${ANI_CLI_EXIT_AFTER_PLAY:-0}}"
+use_external_menu="${NANI_CLI_EXTERNAL_MENU:-${ANI_CLI_EXTERNAL_MENU:-0}}"
+external_menu_normal_window="${NANI_CLI_EXTERNAL_MENU_NORMAL_WINDOW:-${ANI_CLI_EXTERNAL_MENU_NORMAL_WINDOW:-0}}"
+skip_intro="${NANI_CLI_SKIP_INTRO:-${ANI_CLI_SKIP_INTRO:-0}}"
 # shellcheck disable=SC2154
 skip_title="$ANI_CLI_SKIP_TITLE"
 [ -t 0 ] || use_external_menu=1
 hist_dir="${ANI_CLI_HIST_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/nani-cli}"
 [ ! -d "$hist_dir" ] && mkdir -p "$hist_dir"
-histfile="$hist_dir/ani-hsts"
+histfile="$hist_dir/nani-hsts"
 [ ! -f "$histfile" ] && : >"$histfile"
 search="${ANI_CLI_DEFAULT_SOURCE:-scrape}"
 
@@ -474,6 +499,8 @@ while [ $# -gt 0 ]; do
             ;;
         -N | --nextep-countdown) search=nextep ;;
         -U | --update) update_script ;;
+        --stats) show_stats ;;
+        --random) search=random ;;
         *) query="$(printf "%s" "$query $1" | sed "s|^ ||;s| |+|g")" ;;
     esac
     shift
@@ -508,6 +535,28 @@ case "$search" in
         ep_no=$(printf "%s" "$anime_list" | grep "$id" | cut -f2 | sed -nE 's/.*- episode (.+)$/\1/p')
         allanime_title="$(printf "%s" "$title" | cut -d'(' -f1 | tr -d '[:punct:]')"
         ;;
+
+random)
+    if [ "$use_external_menu" = "0" ]; then
+        while [ -z "$query" ]; do
+            printf "\33[2K\r\033[1;36mSearch anime: \033[0m" && read -r query
+        done
+    else
+        [ -z "$query" ] && query=$(printf "" | external_menu "" "Search anime: " "$external_menu_args")
+        [ -z "$query" ] && exit 1
+    fi
+    query=$(printf "%s" "$query" | sed "s| |+|g")
+    anime_list=$(search_anime "$query")
+    [ -z "$anime_list" ] && die "No results found!"
+    result="$(printf "%s" "$anime_list" | rand_line)"
+    [ -z "$result" ] && exit 1
+    title=$(printf "%s" "$result" | cut -f2)
+    allanime_title="$(printf "%s" "$title" | cut -d'(' -f1 | tr -d '[:punct:]')"
+    id=$(printf "%s" "$result" | cut -f1)
+    ep_list=$(episodes_list "$id")
+    [ -z "$ep_no" ] && ep_no=$(printf "%s" "$ep_list" | head -n1)
+    [ -z "$ep_no" ] && exit 1
+    ;;
     *)
         if [ "$use_external_menu" = "0" ]; then
             while [ -z "$query" ]; do
@@ -560,5 +609,3 @@ while cmd=$(printf "next\nreplay\nprevious\nselect\nchange_quality\nquit" | nth 
     [ -z "$ep_no" ] && die "Out of range"
     play
 done
-
-# nani-cli
